// Generated by gencpp from file sphero_node/SpheroCollision.msg
// DO NOT EDIT!


#ifndef SPHERO_NODE_MESSAGE_SPHEROCOLLISION_H
#define SPHERO_NODE_MESSAGE_SPHEROCOLLISION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sphero_node
{
template <class ContainerAllocator>
struct SpheroCollision_
{
  typedef SpheroCollision_<ContainerAllocator> Type;

  SpheroCollision_()
    : header()
    , x(0)
    , y(0)
    , z(0)
    , axis(0)
    , x_magnitude(0)
    , y_magnitude(0)
    , speed(0)
    , timestamp(0)  {
    }
  SpheroCollision_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0)
    , y(0)
    , z(0)
    , axis(0)
    , x_magnitude(0)
    , y_magnitude(0)
    , speed(0)
    , timestamp(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _z_type;
  _z_type z;

   typedef int32_t _axis_type;
  _axis_type axis;

   typedef int32_t _x_magnitude_type;
  _x_magnitude_type x_magnitude;

   typedef int32_t _y_magnitude_type;
  _y_magnitude_type y_magnitude;

   typedef int32_t _speed_type;
  _speed_type speed;

   typedef int32_t _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::sphero_node::SpheroCollision_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sphero_node::SpheroCollision_<ContainerAllocator> const> ConstPtr;

}; // struct SpheroCollision_

typedef ::sphero_node::SpheroCollision_<std::allocator<void> > SpheroCollision;

typedef boost::shared_ptr< ::sphero_node::SpheroCollision > SpheroCollisionPtr;
typedef boost::shared_ptr< ::sphero_node::SpheroCollision const> SpheroCollisionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sphero_node::SpheroCollision_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sphero_node::SpheroCollision_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sphero_node::SpheroCollision_<ContainerAllocator1> & lhs, const ::sphero_node::SpheroCollision_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.axis == rhs.axis &&
    lhs.x_magnitude == rhs.x_magnitude &&
    lhs.y_magnitude == rhs.y_magnitude &&
    lhs.speed == rhs.speed &&
    lhs.timestamp == rhs.timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sphero_node::SpheroCollision_<ContainerAllocator1> & lhs, const ::sphero_node::SpheroCollision_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sphero_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sphero_node::SpheroCollision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sphero_node::SpheroCollision_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sphero_node::SpheroCollision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sphero_node::SpheroCollision_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_node::SpheroCollision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_node::SpheroCollision_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sphero_node::SpheroCollision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "35737f6e6824bac2c5d1f1b54f9c413c";
  }

  static const char* value(const ::sphero_node::SpheroCollision_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x35737f6e6824bac2ULL;
  static const uint64_t static_value2 = 0xc5d1f1b54f9c413cULL;
};

template<class ContainerAllocator>
struct DataType< ::sphero_node::SpheroCollision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sphero_node/SpheroCollision";
  }

  static const char* value(const ::sphero_node::SpheroCollision_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sphero_node::SpheroCollision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int32 x\n"
"int32 y\n"
"int32 z\n"
"int32 axis\n"
"int32 x_magnitude\n"
"int32 y_magnitude \n"
"int32 speed\n"
"int32 timestamp\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sphero_node::SpheroCollision_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sphero_node::SpheroCollision_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.axis);
      stream.next(m.x_magnitude);
      stream.next(m.y_magnitude);
      stream.next(m.speed);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpheroCollision_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sphero_node::SpheroCollision_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sphero_node::SpheroCollision_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.z);
    s << indent << "axis: ";
    Printer<int32_t>::stream(s, indent + "  ", v.axis);
    s << indent << "x_magnitude: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x_magnitude);
    s << indent << "y_magnitude: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y_magnitude);
    s << indent << "speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed);
    s << indent << "timestamp: ";
    Printer<int32_t>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPHERO_NODE_MESSAGE_SPHEROCOLLISION_H
